


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."actualizar_media_lectura"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
BEGIN
  -- Calcular la media
  NEW."Media_Lectura" := (NEW."Izq" + NEW."Cen" + NEW."Dcha") / 3.0;

  -- Calcular la desviación estándar
  NEW."SD_Lectura" := sqrt(
    ((NEW."Izq" - NEW."Media_Lectura")^2 +
     (NEW."Cen" - NEW."Media_Lectura")^2 +
     (NEW."Dcha" - NEW."Media_Lectura")^2) / 3.0
  );

  -- Calcular el coeficiente de variación (CV)
  NEW."CV_Lectura" := NEW."SD_Lectura" / NULLIF(NEW."Media_Lectura",0);

  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."actualizar_media_lectura"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."actualizar_media_lm"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
BEGIN
  -- Calcular la media
  NEW."Media_LM" := (NEW."Izq_LM" + NEW."Dcha_LM") / 2.0;

  -- Calcular la desviación estándar
  NEW."SD_LM" := sqrt(
    ((NEW."Izq_LM" - NEW."Media_LM")^2 +
     (NEW."Dcha_LM" - NEW."Media_LM")^2) / 2.0
  );

  -- Calcular el coeficiente de variación (CV)
  NEW."CV_LM" := NEW."SD_LM" / NULLIF(NEW."Media_LM",0);

  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."actualizar_media_lm"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$ BEGIN INSERT INTO public.profiles (id, username, role) VALUES (NEW.id, NEW.email, 'user'); RETURN NEW; END; $$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Chips" (
    "NumBN_C" bigint NOT NULL,
    "NumLectura_C" bigint NOT NULL,
    "NumLectMarc_C" bigint NOT NULL,
    "NumChip" bigint NOT NULL,
    "Chip_Nombre" "text",
    "FC" bigint,
    "Coment_Chip" "text",
    "Repetir_Chip" smallint
);


ALTER TABLE "public"."Chips" OWNER TO "postgres";


COMMENT ON COLUMN "public"."Chips"."Repetir_Chip" IS '1 = repetir esta carga de chip (misma muestra/lectura/LM/ NumChip); NULL o 0 = ok.';



CREATE TABLE IF NOT EXISTS "public"."DChips" (
    "NumChip_D" bigint NOT NULL,
    "Nombre_Chip" "text" NOT NULL
);


ALTER TABLE "public"."DChips" OWNER TO "postgres";


ALTER TABLE "public"."DChips" ALTER COLUMN "NumChip_D" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DChips_NumChip_D_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."DDx" (
    "Cod" bigint NOT NULL,
    "Dx" "text"
);


ALTER TABLE "public"."DDx" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."DMuestra" (
    "Cod" bigint NOT NULL,
    "TipoMuestra" "text"
);


ALTER TABLE "public"."DMuestra" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Lectura" (
    "NumBN_L" bigint NOT NULL,
    "NumLectura" bigint NOT NULL,
    "Fecha_lectura" "text",
    "Izq" double precision,
    "Cen" double precision,
    "Dcha" double precision,
    "Coment_Lectura" "text",
    "Estado_Lectura" bigint,
    "Marcado" bigint,
    "Media_Lectura" numeric,
    "SD_Lectura" numeric,
    "CV_Lectura" numeric
);


ALTER TABLE "public"."Lectura" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Lecturas_Marcado" (
    "NumBN_LM" bigint NOT NULL,
    "NumLectura_LM" bigint NOT NULL,
    "NumLectMarc" bigint NOT NULL,
    "Fecha_Lect_Marc" "text",
    "Cargado_LM" bigint,
    "Izq_LM" double precision,
    "Dcha_LM" double precision,
    "PN_LM" "text",
    "LN_LM" "text",
    "Exp_LM" "text",
    "Estado_LMarcado" bigint,
    "Comentario_LMarcado" "text",
    "Media_LM" numeric,
    "SD_LM" numeric,
    "CV_LM" numeric,
    "PNM_LM" "text",
    "LNM_LM" "text",
    "ExpM_LM" "text"
);


ALTER TABLE "public"."Lecturas_Marcado" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Marcado" (
    "NumBN_M" bigint NOT NULL,
    "NumLectura_M" bigint NOT NULL,
    "Fecha_Marcado" "text",
    "PN_Membrana" "text",
    "LN_Membrana" bigint,
    "Exp_Membrana" "text",
    "Comentario_Membrana" "text",
    "Fecha_Lect_Marc" "text",
    "Cargado_M" "text",
    "Izq_M" double precision,
    "Dcha_M" double precision,
    "PN_M" "text",
    "LN_M" bigint,
    "Exp_M" "text",
    "Estado_Marcado" bigint
);


ALTER TABLE "public"."Marcado" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Muestras" (
    "NumBN" bigint NOT NULL,
    "Posic" "text",
    "Petic" bigint,
    "Dx" bigint,
    "Muestra" bigint,
    "Proces" "text",
    "Coment_Muestra" "text",
    "Chip_Muestra" "text",
    "Chip_FC_Muestra" "text",
    "Pellet" "text",
    "Fecha" "text",
    "PN" "text",
    "LN" bigint,
    "Exp" "text",
    "Medusa" "text",
    "Coment_Extracc" "text",
    "Estado_Muestra" bigint,
    "Visco_grado" smallint
);


ALTER TABLE "public"."Muestras" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Preselect" (
    "Petic_Preselect" bigint NOT NULL,
    "Coment_Preselect" "text",
    "NumBN_Preselect" bigint,
    "Fecha_Preselect" "text",
    "Dx_Preselect" bigint
);


ALTER TABLE "public"."Preselect" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Tags" (
    "Tag_Number" bigint NOT NULL,
    "Tag_Name" "text" NOT NULL,
    "Tag_Color" "text" NOT NULL,
    "Created_At" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Tags" OWNER TO "postgres";


ALTER TABLE "public"."Tags" ALTER COLUMN "Tag_Number" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Tags_Tag_Number_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE IF NOT EXISTS "public"."Muestra_Tags" (
    "NumBN_Tag" bigint NOT NULL,
    "Tag_Number" bigint NOT NULL,
    "Created_At" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Muestra_Tags" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "username" "text",
    "role" "text" DEFAULT 'user'::"text"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


ALTER TABLE ONLY "public"."Chips"
    ADD CONSTRAINT "Chips_pkey" PRIMARY KEY ("NumBN_C", "NumLectura_C", "NumLectMarc_C", "NumChip");



ALTER TABLE ONLY "public"."DChips"
    ADD CONSTRAINT "DChips_pkey" PRIMARY KEY ("NumChip_D");



ALTER TABLE ONLY "public"."DDx"
    ADD CONSTRAINT "DDx_pkey" PRIMARY KEY ("Cod");



ALTER TABLE ONLY "public"."DMuestra"
    ADD CONSTRAINT "DMuestra_pkey" PRIMARY KEY ("Cod");



ALTER TABLE ONLY "public"."Lectura"
    ADD CONSTRAINT "Lectura_pkey" PRIMARY KEY ("NumBN_L", "NumLectura");



ALTER TABLE ONLY "public"."Lecturas_Marcado"
    ADD CONSTRAINT "Lecturas_Marcado_pkey" PRIMARY KEY ("NumBN_LM", "NumLectura_LM", "NumLectMarc");



ALTER TABLE ONLY "public"."Marcado"
    ADD CONSTRAINT "Marcado_pkey" PRIMARY KEY ("NumBN_M", "NumLectura_M");



ALTER TABLE ONLY "public"."Muestras"
    ADD CONSTRAINT "Muestras_pkey" PRIMARY KEY ("NumBN");



ALTER TABLE ONLY "public"."Preselect"
    ADD CONSTRAINT "Preselect_NumBN_Preselect_key" UNIQUE ("NumBN_Preselect");



ALTER TABLE ONLY "public"."Preselect"
    ADD CONSTRAINT "Preselect_pkey" PRIMARY KEY ("Petic_Preselect");



ALTER TABLE ONLY "public"."Tags"
    ADD CONSTRAINT "Tags_pkey" PRIMARY KEY ("Tag_Number");



ALTER TABLE ONLY "public"."Tags"
    ADD CONSTRAINT "Tags_Tag_Color_hex_chk" CHECK (("Tag_Color" ~ '^#[0-9A-Fa-f]{6}$'::"text"));



ALTER TABLE ONLY "public"."Muestra_Tags"
    ADD CONSTRAINT "Muestra_Tags_pkey" PRIMARY KEY ("NumBN_Tag", "Tag_Number");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "trigger_media_lectura" BEFORE INSERT OR UPDATE OF "Izq", "Cen", "Dcha" ON "public"."Lectura" FOR EACH ROW EXECUTE FUNCTION "public"."actualizar_media_lectura"();



CREATE OR REPLACE TRIGGER "trigger_media_lm" BEFORE INSERT OR UPDATE ON "public"."Lecturas_Marcado" FOR EACH ROW EXECUTE FUNCTION "public"."actualizar_media_lm"();



CREATE UNIQUE INDEX "Tags_Tag_Name_ci_uniq" ON "public"."Tags" USING "btree" ("lower"("Tag_Name"));



CREATE INDEX "Muestra_Tags_Tag_Number_idx" ON "public"."Muestra_Tags" USING "btree" ("Tag_Number");



CREATE INDEX "Muestra_Tags_NumBN_Tag_idx" ON "public"."Muestra_Tags" USING "btree" ("NumBN_Tag");



ALTER TABLE ONLY "public"."Chips"
    ADD CONSTRAINT "Chips_NumBN_C_NumLectura_C_NumLectMarc_C_fkey" FOREIGN KEY ("NumBN_C", "NumLectura_C", "NumLectMarc_C") REFERENCES "public"."Lecturas_Marcado"("NumBN_LM", "NumLectura_LM", "NumLectMarc") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Chips"
    ADD CONSTRAINT "Chips_NumChip_fkey" FOREIGN KEY ("NumChip") REFERENCES "public"."DChips"("NumChip_D") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Lectura"
    ADD CONSTRAINT "Lectura_NumBN_L_fkey" FOREIGN KEY ("NumBN_L") REFERENCES "public"."Muestras"("NumBN") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Lecturas_Marcado"
    ADD CONSTRAINT "Lecturas_Marcado_NumBN_LM_NumLectura_LM_fkey" FOREIGN KEY ("NumBN_LM", "NumLectura_LM") REFERENCES "public"."Marcado"("NumBN_M", "NumLectura_M") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Marcado"
    ADD CONSTRAINT "Marcado_NumBN_M_NumLectura_M_fkey" FOREIGN KEY ("NumBN_M", "NumLectura_M") REFERENCES "public"."Lectura"("NumBN_L", "NumLectura") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Muestras"
    ADD CONSTRAINT "Muestras_Dx_fkey" FOREIGN KEY ("Dx") REFERENCES "public"."DDx"("Cod") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Muestras"
    ADD CONSTRAINT "Muestras_Muestra_fkey" FOREIGN KEY ("Muestra") REFERENCES "public"."DMuestra"("Cod") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Preselect"
    ADD CONSTRAINT "Preselect_Dx_Preselect_fkey" FOREIGN KEY ("Dx_Preselect") REFERENCES "public"."DDx"("Cod") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Preselect"
    ADD CONSTRAINT "Preselect_NumBN_Preselect_fkey" FOREIGN KEY ("NumBN_Preselect") REFERENCES "public"."Muestras"("NumBN") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Muestra_Tags"
    ADD CONSTRAINT "Muestra_Tags_NumBN_Tag_fkey" FOREIGN KEY ("NumBN_Tag") REFERENCES "public"."Muestras"("NumBN") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Muestra_Tags"
    ADD CONSTRAINT "Muestra_Tags_Tag_Number_fkey" FOREIGN KEY ("Tag_Number") REFERENCES "public"."Tags"("Tag_Number") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Allow all to all" ON "public"."Chips" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all to all" ON "public"."DChips" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all to all" ON "public"."DDx" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all to all" ON "public"."DMuestra" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all to all" ON "public"."Lectura" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all to all" ON "public"."Lecturas_Marcado" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all to all" ON "public"."Marcado" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all to all" ON "public"."Muestras" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all to all" ON "public"."Preselect" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all to all" ON "public"."Tags" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all to all" ON "public"."Muestra_Tags" USING (true) WITH CHECK (true);



CREATE POLICY "Allow logged-in users to read their own profile" ON "public"."profiles" FOR SELECT USING (("username" = "auth"."email"()));



ALTER TABLE "public"."Chips" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."DChips" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."DDx" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."DMuestra" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Lectura" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Lecturas_Marcado" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Marcado" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Muestras" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Preselect" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Tags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Muestra_Tags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."actualizar_media_lectura"() TO "anon";
GRANT ALL ON FUNCTION "public"."actualizar_media_lectura"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."actualizar_media_lectura"() TO "service_role";



GRANT ALL ON FUNCTION "public"."actualizar_media_lm"() TO "anon";
GRANT ALL ON FUNCTION "public"."actualizar_media_lm"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."actualizar_media_lm"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON TABLE "public"."Chips" TO "anon";
GRANT ALL ON TABLE "public"."Chips" TO "authenticated";
GRANT ALL ON TABLE "public"."Chips" TO "service_role";



GRANT ALL ON TABLE "public"."DChips" TO "anon";
GRANT ALL ON TABLE "public"."DChips" TO "authenticated";
GRANT ALL ON TABLE "public"."DChips" TO "service_role";



GRANT ALL ON SEQUENCE "public"."DChips_NumChip_D_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DChips_NumChip_D_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DChips_NumChip_D_seq" TO "service_role";



GRANT ALL ON TABLE "public"."DDx" TO "anon";
GRANT ALL ON TABLE "public"."DDx" TO "authenticated";
GRANT ALL ON TABLE "public"."DDx" TO "service_role";



GRANT ALL ON TABLE "public"."DMuestra" TO "anon";
GRANT ALL ON TABLE "public"."DMuestra" TO "authenticated";
GRANT ALL ON TABLE "public"."DMuestra" TO "service_role";



GRANT ALL ON TABLE "public"."Lectura" TO "anon";
GRANT ALL ON TABLE "public"."Lectura" TO "authenticated";
GRANT ALL ON TABLE "public"."Lectura" TO "service_role";



GRANT ALL ON TABLE "public"."Lecturas_Marcado" TO "anon";
GRANT ALL ON TABLE "public"."Lecturas_Marcado" TO "authenticated";
GRANT ALL ON TABLE "public"."Lecturas_Marcado" TO "service_role";



GRANT ALL ON TABLE "public"."Marcado" TO "anon";
GRANT ALL ON TABLE "public"."Marcado" TO "authenticated";
GRANT ALL ON TABLE "public"."Marcado" TO "service_role";



GRANT ALL ON TABLE "public"."Muestras" TO "anon";
GRANT ALL ON TABLE "public"."Muestras" TO "authenticated";
GRANT ALL ON TABLE "public"."Muestras" TO "service_role";



GRANT ALL ON TABLE "public"."Preselect" TO "anon";
GRANT ALL ON TABLE "public"."Preselect" TO "authenticated";
GRANT ALL ON TABLE "public"."Preselect" TO "service_role";



GRANT ALL ON TABLE "public"."Tags" TO "anon";
GRANT ALL ON TABLE "public"."Tags" TO "authenticated";
GRANT ALL ON TABLE "public"."Tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Tags_Tag_Number_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Tags_Tag_Number_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Tags_Tag_Number_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Muestra_Tags" TO "anon";
GRANT ALL ON TABLE "public"."Muestra_Tags" TO "authenticated";
GRANT ALL ON TABLE "public"."Muestra_Tags" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







